"""Regression tests for CR-02 / WR-03 — the `.mdc` rules file lifecycle.

CR-02: ``cursor.install()`` correctly refuses to overwrite a generator-managed
``.cursor/rules/dual-memory.mdc`` (SM-9a). ``cursor.uninstall()`` deleted it
with no guard, no backup and no warning — and ``repair`` is defined as
uninstall-then-install, so ``repair`` destroyed exactly the file ``install``
refuses to touch. The reinstall half then saw a *non-existent* target, which
short-circuits ``_looks_generated``, and wrote the packaged copy over it.

Worse, ``repair --dry-run`` printed "appears generator-managed — leaving it
untouched" and the real run then deleted it: a prediction/reality divergence on
top of silent data loss, with no way to opt out.

WR-03: every other target gets a ``.bak.<ns>`` snapshot — JSON via
``atomic_write_json``, ``CLAUDE.md``/``AGENTS.md`` explicitly. The ``.mdc`` got
neither on overwrite (``shutil.copy2``) nor on removal (``unlink``). That is the
non-guarded half of CR-02 and would remain a data-loss path even once the guard
landed, for a file that is edited but not *marked*.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

MARKED_MDC = """---
# AUTO-GENERATED by my-repo-generator — DO NOT EDIT
---
my custom rules
"""

# Deliberately carries none of the `generated` / `do-not-edit` /
# `auto-generated` tokens, and no sibling manifest: the "user hand-edited an
# unmarked file" case WR-03 is about.
UNMARKED_MDC = """---
description: my own dual-memory rules
---
hand written content worth keeping
"""


@pytest.fixture
def home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setattr(Path, "home", classmethod(lambda cls: tmp_path))
    return tmp_path


@pytest.fixture
def project(tmp_path_factory: pytest.TempPathFactory, monkeypatch: pytest.MonkeyPatch) -> Path:
    cwd = tmp_path_factory.mktemp("workspace")
    monkeypatch.chdir(cwd)
    return cwd


def _seed_mdc(project: Path, content: str) -> Path:
    target = project / ".cursor" / "rules" / "dual-memory.mdc"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target


def _seed_installed_cursor(project: Path) -> None:
    """Minimal `.cursor/mcp.json` so repair's auto-detect sees cursor."""
    mcp = project / ".cursor" / "mcp.json"
    mcp.parent.mkdir(parents=True, exist_ok=True)
    mcp.write_text(json.dumps({"mcpServers": {"supamem": {"command": "supamem"}}}), "utf-8")


def _baks(target: Path) -> list[Path]:
    return sorted(target.parent.glob(target.name + ".bak.*"))


# ─────────────────────────── CR-02: the guard ──────────────────────────────


def test_uninstall_preserves_generator_managed_mdc(home: Path, project: Path) -> None:
    """Pre-fix failure: the file was unlinked unconditionally — no guard, no
    backup, no warning."""
    from supamem.install.cursor import uninstall

    target = _seed_mdc(project, MARKED_MDC)
    uninstall()

    assert target.exists(), "a generator-managed .mdc must survive uninstall"
    assert target.read_text(encoding="utf-8") == MARKED_MDC


def test_repair_preserves_generator_managed_mdc_byte_identical(
    home: Path, project: Path
) -> None:
    """CR-02 core reproduction: ``repair`` = uninstall + install, so it deleted
    the guarded file and then wrote the packaged copy over it.

    Pre-fix failure: `my custom rules` gone, replaced by the packaged copy,
    with no `.bak` anywhere in `.cursor/rules/`.
    """
    from supamem.install import repair

    _seed_installed_cursor(project)
    target = _seed_mdc(project, MARKED_MDC)

    repair("cursor", skip_models=True, skip_patch_agents=True)

    assert target.read_text(encoding="utf-8") == MARKED_MDC, (
        "repair must not destroy the file install refuses to overwrite"
    )


def test_repair_dry_run_promise_matches_real_run_for_marked_mdc(
    home: Path, project: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The dry run explicitly promises "leaving it untouched". The real run must
    honour that promise — prediction/reality divergence is the CR-02 tell."""
    from supamem.install import repair

    _seed_installed_cursor(project)
    target = _seed_mdc(project, MARKED_MDC)

    repair("cursor", dry_run=True, skip_models=True, skip_patch_agents=True)
    dry_out = capsys.readouterr().out
    assert "generator-managed" in dry_out, dry_out
    before = target.read_bytes()

    repair("cursor", skip_models=True, skip_patch_agents=True)
    assert target.read_bytes() == before


def test_force_cursor_rules_still_allows_removal(home: Path, project: Path) -> None:
    """The escape hatch must exist on the removal side too — otherwise the fix
    just inverts the trap (no way to opt *in* to removal)."""
    from supamem.install.cursor import uninstall

    target = _seed_mdc(project, MARKED_MDC)
    uninstall(force_cursor_rules=True)
    assert not target.exists()
    # ...and the content is still recoverable (WR-03).
    baks = _baks(target)
    assert len(baks) == 1
    assert baks[0].read_text(encoding="utf-8") == MARKED_MDC


def test_uninstall_dry_run_never_removes_or_backs_up(home: Path, project: Path) -> None:
    """SM-7a: dry run writes nothing at all — no unlink, no `.bak`."""
    from supamem.install.cursor import uninstall

    target = _seed_mdc(project, UNMARKED_MDC)
    uninstall(dry_run=True)
    assert target.read_text(encoding="utf-8") == UNMARKED_MDC
    assert _baks(target) == []


# ─────────────────────────── WR-03: the backups ────────────────────────────


def test_uninstall_backs_up_unmarked_mdc_before_removing(home: Path, project: Path) -> None:
    """WR-03: an unmarked-but-hand-edited .mdc was unrecoverable after a single
    warning line, unlike every sibling target."""
    from supamem.install.cursor import uninstall

    target = _seed_mdc(project, UNMARKED_MDC)
    uninstall()

    assert not target.exists(), "an unmarked .mdc is still supamem's to remove"
    baks = _baks(target)
    assert len(baks) == 1, f"expected exactly one .bak sibling, got {baks}"
    assert baks[0].read_text(encoding="utf-8") == UNMARKED_MDC


def test_install_backs_up_unmarked_mdc_before_overwriting(
    home: Path, project: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """WR-03: ``shutil.copy2`` clobbered user content with no snapshot, while
    the sibling warning for hooks.json could honestly say "(backup retained)"."""
    from supamem.install.cursor import install

    target = _seed_mdc(project, UNMARKED_MDC)
    install()

    assert target.read_text(encoding="utf-8") != UNMARKED_MDC, "packaged copy wins"
    baks = _baks(target)
    assert len(baks) == 1, f"expected exactly one .bak sibling, got {baks}"
    assert baks[0].read_text(encoding="utf-8") == UNMARKED_MDC
    # The warning must now be able to make the claim its sibling makes.
    assert "backup" in capsys.readouterr().out.lower()


def test_install_dry_run_writes_no_mdc_backup(home: Path, project: Path) -> None:
    from supamem.install.cursor import install

    target = _seed_mdc(project, UNMARKED_MDC)
    install(dry_run=True)
    assert target.read_text(encoding="utf-8") == UNMARKED_MDC
    assert _baks(target) == []
